version: '2'
services:
  irc-worker:
    image: patt1293/chaturbae-irc
    logging:
      driver: gelf
      options:
        gelf-address: udp://107.155.93.182:12201
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
    environment:
      DEBUG: "chaturbae:*"
    ports:
      - "8081"
  nsfw-api:
    image: patt1293/nsfw_api
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
    environment:
      DEBUG: "chaturbae:*"
    environment:
      PORT: "5000"
    ports:
      - "5000"
